### ISSUE TITLE
[service-request]: create intro/outro for videos that others can apply on their content

### ISSUE THREAD

**Issue by pavelsevcik** [dstudio-earth/inbox#38]
### Contact Details

Nila Phi

### Request on behalf of organization

Hypha

### REQUIREMENTS

- intro/outro as per [Game of SEEDS - Buy SEEDS](https://www.youtube.com/watch?v=Q5Rso-hYzPo&list=PLdkOHIpxNbGbYYunSK7fuTanFFRe92mpa&index=2)
- Format: HORIZONTAL
- [Video resolution & aspect ratios](https://support.google.com/youtube/answer/6375112):
- 2160p: 3840x2160
- 1440p: 2560x1440
- 1080p: 1920x1080
- 720p: 1280x720

#### INTRO
- first 4 sec animation of seeds icon to seeds logo
- add extra few seconds after logo fades out to allow creators fade in their content? if we're doing it like [first 2 seconds in this video](https://www.youtube.com/watch?v=IyTv_SR2uUo) then extra few sec is not required?

#### OUTRO
- start when leafs going over orb (orb, subtitles not included in this outro)

![image](https://user-images.githubusercontent.com/5997075/127754710-3c66baf8-ee51-4a4f-aa28-946c92c7ab28.png)

- Change "Let's play" to "Are You ready to play?"

![image](https://user-images.githubusercontent.com/5997075/127754713-cc8a380e-5d29-4ca6-810c-ecf15e18fcef.png)

- No need more variants of text on outro.

### Deliverables/Assets purpose, intended use

Youtube

### Terms of Service

- [X] I agree to follow this dSTUDIO's Terms of Service

**Comment by pavelsevcik** [comment]
FYI: As per discussion with Nila, animation IS in line with [logoreveal-usage.pdf](https://github.com/dstudio-earth/inbox/files/6874703/logoreveal-usage.pdf), so no need any changes

**Comment by nila-phi** [comment]
if the sound signature is available, i'd like for that to be added as well. but only if it's available.

**Comment by pavelsevcik** [comment]
@nila-phi as per your message earlier

>I'M JUST ASKING GIAN TO DO A SOUND SIGNATURE TO APPLY AS WELL

I thought that you're dealing with @gianberselli directly and you'll just get video asset from dSTUDIO and audio asset from Gian, so community can apply those as they need, for that reason I did not listed sound signature under requirements nor get in contact with Gian to get quote from him nor included it in quote.

BUT now it seems, that you want something like [first 2 seconds in this video](https://www.youtube.com/watch?v=IyTv_SR2uUo), can you confirm that? Cause from last interaction with Gian is obvious, that he's not aware of this particular request.

Thanks

Pavel

**Comment by maniksethisuwan** [comment]
Good to go regarding the animations. Awaiting final confirmation and instructions.

**Comment by gianberselli** [comment]
Sound Signature is done as well

**Comment by nila-phi** [comment]
@gianberselli @pavelsevcik Ok, so we'll do 2 different quotes, one for the video assets and one for the sound assets. 

@pavelsevcik the quest in the DHO for the video assets will pass in 1 day (unless a bunch of new people simultaneously join together against it...highly unlikely)

**Comment by maniksethisuwan** [comment]
Dear @nila-phi thank you so much for all your help, and being here for us. After learning the timeline from Gian and Basil, who have been working on the sound since February, I was able to come up with a quote for the Sound Signatures, and just emailed you an everyone. Please do kindly have a look, with kindness and understanding, and do help us where you can.

Most sincerely.

**Comment by maniksethisuwan** [comment]
Hey @gianberselli working on the animations now. You wanna send me the sound signature audio file so I could make preview edits? Just to save time that is.

**Comment by maniksethisuwan** [comment]
@nila-phi 
Seeds Logo Intro 12 seconds, variations

https://user-images.githubusercontent.com/35344633/128119633-405b1598-c005-450d-9dc7-c52c41f31802.mp4



https://user-images.githubusercontent.com/35344633/128119622-fa106cfe-5dad-4d09-9363-6209e6eed919.mp4



https://user-images.githubusercontent.com/35344633/128119605-6413d447-a52c-415a-bf55-a63a07fbdd84.mp4





https://user-images.githubusercontent.com/35344633/128119556-9deb423c-35f7-4cde-9443-7dfb030fee9f.mp4


https://user-images.githubusercontent.com/35344633/128119572-2ea950e0-c417-4598-bcae-db851478f5c6.mp4


https://user-images.githubusercontent.com/35344633/128119585-6d0f7f74-f442-4c54-8616-e31cfdb36298.mp4

**Comment by maniksethisuwan** [comment]
@nila-phi
Seeds Logo Outro 10 seconds, variations


https://user-images.githubusercontent.com/35344633/128119707-7c745458-7865-4c9a-bc2d-6279d220da32.mp4


https://user-images.githubusercontent.com/35344633/128119711-c305994f-1304-403e-9dfc-fa9ae51bec44.mp4


https://user-images.githubusercontent.com/35344633/128119713-e476d254-8185-4acd-88d5-5093ad87264d.mp4


https://user-images.githubusercontent.com/35344633/128119715-c5f01aa6-124a-45c4-b9fb-f535b681c24e.mp4


https://user-images.githubusercontent.com/35344633/128119717-6e24d649-c748-4de2-abe3-2d4c98041523.mp4


https://user-images.githubusercontent.com/35344633/128119718-fc405e53-f720-485e-b389-af7a3e5ccffa.mp4

**Comment by nila-phi** [comment]
@maniksethisuwan I would really like for all communications to be here (all in one place) rather than distributed between emails, discord and GitHub. Thanks so much

**Comment by nila-phi** [comment]
@pavelsevcik the quest outlined that delivery will be 2-4 days upon approval. now that it is approved, when can we expect to have the intro & outro features?

**Comment by nila-phi** [comment]
I think it's best to have the sound signature separately for a couple reasons:
- we will need to do another quest for it on the DHO
- we can use it as a separate asset to people using it. (option to use it, option to leave it out)

**Comment by maniksethisuwan** [comment]
Dear @nila-phi I sent Basil these four last night/this morning. Do have a look. The size of Seeds text wouldn't scale proportionately from the vertical versions, so I made here two versions of each with text size options 45percent and 60percent so you can choose. Few seconds are kept in after logo fades after Intro, for creators to input their titling/text, or overlap with video when our jingle fades. Sound signature is also added into both Intro and Outro videos, so there's a timing reference. Don't forget to click unmute on the volume button when you play them here.

Do let me know if all seems good.

Cheers.

https://user-images.githubusercontent.com/35344633/128200685-df419c02-3a28-4a05-abe1-8095a5bad07b.mp4


https://user-images.githubusercontent.com/35344633/128200686-7be564c7-bd2b-42bd-b428-7e34dc660dbe.mp4


https://user-images.githubusercontent.com/35344633/128200697-8933145e-3797-43c9-9543-4aac26521f1b.mp4




https://user-images.githubusercontent.com/35344633/128200674-a95a7715-8c6a-4e75-8bc0-5aebf5023f3d.mp4

**Comment by pavelsevcik** [comment]
> @pavelsevcik the quest outlined that delivery will be 2-4 days upon approval. now that it is approved, when can we expect to have the intro & outro features?

Hi @nila-phi,

assets created, uploaded to public drive, descriptions, link to drive at https://public-assets-drive.dstudio.earth/projects/seeds.
Please check videos and reply with feedback, confirmation of delivery.

Thank you

Pavel

**Comment by nila-phi** [comment]
@pavelsevcik these look great! how do we get you paid for this? can dstudio do a quest completion contribution on the who?

**Comment by pavelsevcik** [comment]
> @pavelsevcik these look great! how do we get you paid for this? can dstudio do a quest completion contribution on the who?

@nila-phi Thank you! We'll submit contribution under `dstudioproto` referring to quest. Closing this issue. Feel free to reopen if need to clarify anything.
