### ISSUE TITLE
[service-request]: Create sound signature for SEEDS

### ISSUE THREAD

**Issue by pavelsevcik** [dstudio-earth/inbox#41]
### Contact Details

Nila

### Request on behalf of organization

SEEDS

### Deliverables/Assets

sound signature

### Terms of Service

- [X] I agree to follow this dSTUDIO's Terms of Service

**Comment by maniksethisuwan** [comment]
Dear Nila Hope you are doing well. Hereby please allow me to attach the email for SEEDs sound signature budget and PDF budget file here, for your reference and follow-up. You said will submit this as a new project at Hyphaa. Do kindly let me know if anything I can do to help, and how it goes?

Thanks.



[budget dSTU-210803 SEEDS Sound Signature.pdf](https://github.com/dstudio-earth/inbox/files/6973248/budget.dSTU-210803.SEEDS.Sound.Signature.pdf)

**Comment by pavelsevcik** [comment]
@nila-phi can you please check quote and re if need clarify anything or if you can submit quest as is.

Thank you

Pavel

**Comment by nila-phi** [comment]
@pavelsevcik @maniksethisuwan 
this looks good to me. 
who will post it on the who? do you guys want to do that, or shall i?

**Comment by pavelsevcik** [comment]
@nila-phi
- we'll make it available same way as intro/outro
- let you verify delivery
- then we'll submit it as quest-completed and we'll refer to you as sponsor / verifier

**Comment by pavelsevcik** [comment]
Hi @nila-phi,

assets created, uploaded to public drive, descriptions, link to drive at https://public-assets-drive.dstudio.earth/projects/seeds. Please check `SEEDS-SOUNDS-SIGNATURE-for-videos-by-community` and reply with confirmation of delivery.

After that we'll submit quest-completed under dstudioproto.


Thank you

Pavel

**Comment by nila-phi** [comment]
hey @pavelsevcik looks good to me. it would be great if we could also have the sounds signature added to the video intro/outros so the total assets looked like:
- intro silent (various forms)
- intro with sound signature (various forms)
- intro sound signature
- outro silent (various forms)
- outro with sound signature (various forms)
- outro sound signature

beyond that, it looks great to me. what actions need to be taken from my side?

**Comment by maniksethisuwan** [comment]
Various forms meaning various resolution sizes?

**Comment by pavelsevcik** [comment]
@nila-phi done, all at https://public-assets-drive.dstudio.earth/projects/seeds 

next step is in our corner — well submit under dstudioproto quest completed

**Comment by nila-phi** [comment]
@maniksethisuwan yes, "various forms" meant various resolution sizes ;)
@pavelsevcik thanks so much. i just saw them.
